/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/is6cAGvIOy3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarFallback, Avatar } from "@/components/ui/avatar"

export function ProfileLogo() {
  return (
    (<div
      className="flex flex-col items-center justify-center gap-6 py-12 md:py-16">
      <div className="flex flex-col items-center gap-4">
        <Avatar className="h-20 w-20">
          <AvatarFallback>USER</AvatarFallback>
        </Avatar>
        <div className="grid gap-1 text-center">
          <div className="text-2xl font-bold">jared@acme.inc</div>
        </div>
      </div>
    </div>)
  );
}
